import os

import numpy as np
import pytest

from zombiesai import spec
from zombiesai.demos.capture import ReplayInput
from zombiesai.demos.clips import load_clip
from zombiesai.demos.game_settings import (
    candidate_configs,
    implied_counts_per_degree,
    parse_config,
    read_settings,
    settings_warnings,
)
from zombiesai.demos.inputs import InputConfig
from zombiesai.demos.recorder import RecorderConfig, record

# Trimmed from a real Proton install's config.cfg.
CONFIG = """// generated by Call of Duty, do not modify
unbindall
bind TAB "+scores"
bind MOUSE1 "+attack"
bind MOUSE2 "+speed_throw"
bind MWHEELDOWN "weapnext"
seta cg_fov "65"
seta input_viewSensitivity "1"
seta m_filter "0"
seta m_pitch "0.022"
seta m_yaw "0.022"
seta r_aspectRatio "wide 16:9"
seta r_fullscreen "0"
seta r_mode "2560x1440"
seta sensitivity "5"
seta snd_volume "0.8"
"""


def profile(root, name="$$$", text=CONFIG, mtime=None):
    path = (
        root / ".steam" / "steam" / "steamapps" / "compatdata" / "10090" / "pfx" / "drive_c" / "users"
        / "steamuser" / "AppData" / "Local" / "Activision" / "CoDWaW" / "players" / "profiles" / name / "config.cfg"
    )
    path.parent.mkdir(parents=True)
    path.write_text(text)
    if mtime is not None:
        os.utime(path, (mtime, mtime))
    return path


def test_the_config_is_read_into_dvars_and_binds():
    dvars, binds = parse_config(CONFIG)
    assert dvars["sensitivity"] == "5" and dvars["r_mode"] == "2560x1440"
    assert binds["MOUSE2"] == "+speed_throw" and binds["MWHEELDOWN"] == "weapnext"


def test_the_config_implies_the_counts_per_degree_the_labels_need():
    assert implied_counts_per_degree({"sensitivity": "5", "m_yaw": "0.022"}) == pytest.approx(9.0909, abs=1e-3)
    assert implied_counts_per_degree({"sensitivity": "5"}) is None
    assert implied_counts_per_degree({"sensitivity": "0", "m_yaw": "0.022"}) is None


def test_the_newest_profile_in_the_proton_prefix_is_the_one_read(tmp_path):
    profile(tmp_path, "old", CONFIG.replace('sensitivity "5"', 'sensitivity "3"'), mtime=1_000)
    profile(tmp_path, "$$$", mtime=2_000)
    assert [p.parent.name for p in candidate_configs(tmp_path)] == ["$$$", "old"]
    settings = read_settings(home=tmp_path)
    assert settings["dvars"]["sensitivity"] == "5"
    assert "snd_volume" not in settings["dvars"]  # only what bears on a recording
    assert settings["binds"]["MOUSE1"] == "+attack"


def test_no_game_on_this_machine_is_none_not_an_error(tmp_path):
    assert read_settings(home=tmp_path) is None
    assert "couldn't find" in settings_warnings(None, 9.09)[0]


def test_a_matching_setup_has_nothing_to_warn_about(tmp_path):
    assert settings_warnings(read_settings(profile(tmp_path)), 9.09) == []


@pytest.mark.parametrize(
    ("change", "cpd", "says"),
    [
        (('sensitivity "5"', 'sensitivity "10"'), 9.09, "implies 4.55"),
        (("", ""), 6.4, "implies 9.09"),
        (('m_filter "0"', 'm_filter "1"'), 9.09, "smoothing"),
        (('bind MOUSE2 "+speed_throw"', 'bind MOUSE2 "+toggleads_throw"'), 9.09, "toggle-ADS"),
    ],
)
def test_settings_that_would_spoil_a_recording_are_named_before_it_starts(tmp_path, change, cpd, says):
    settings = read_settings(profile(tmp_path, text=CONFIG.replace(*change)))
    warnings = settings_warnings(settings, cpd)
    assert len(warnings) == 1 and says in warnings[0]


class OneFrame:
    def read(self):
        return np.zeros(spec.PIXELS_SHAPE, np.uint8)

    def close(self):
        pass


def test_the_settings_are_in_the_clip_before_the_first_step(tmp_path):
    settings = read_settings(profile(tmp_path))
    config = RecorderConfig(max_steps=3, realtime=False, input=InputConfig(counts_per_degree=9.09))
    path = record(OneFrame(), ReplayInput([]), tmp_path / "demo", config, progress_every=0,
                  annotations={"game_settings": settings})
    stamped = load_clip(path).manifest["game_settings"]
    assert stamped["dvars"]["sensitivity"] == "5"
    assert stamped["implied_counts_per_degree"] == pytest.approx(9.09, abs=0.01)
